/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package window;

import data.*;

/**
 *
 * @author Bhadresh
 */
public class add_sale extends javax.swing.JFrame {

    /**
     * Creates new form purchase
     */
    add_sale p;
    
    public add_sale() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ic = new javax.swing.JLabel();
        pro_name = new javax.swing.JTextField();
        pn = new javax.swing.JLabel();
        party_name = new javax.swing.JTextField();
        pan = new javax.swing.JLabel();
        item_code = new javax.swing.JTextField();
        pie = new javax.swing.JLabel();
        rate = new javax.swing.JTextField();
        ra = new javax.swing.JLabel();
        piece = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        sell_date = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ic.setText("Item Code");
        jPanel1.add(ic, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 144, 80, -1));
        jPanel1.add(pro_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 120, -1));

        pn.setText("Product Name");
        jPanel1.add(pn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 104, 80, -1));
        jPanel1.add(party_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 120, -1));

        pan.setText("Party Name");
        jPanel1.add(pan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 64, 80, -1));
        jPanel1.add(item_code, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 120, -1));

        pie.setText("Piece");
        jPanel1.add(pie, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 184, 100, -1));
        jPanel1.add(rate, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 120, -1));

        ra.setText("Rate");
        jPanel1.add(ra, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 224, 80, -1));
        jPanel1.add(piece, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 120, -1));

        add.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        add.setText("Add Selling Detail");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 260, 30));

        jLabel10.setText("Selling Date");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 24, 80, -1));
        jPanel1.add(sell_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 120, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed

        db_connection c = new db_connection(this);
        c.insert_selling_query();
        setVisible(false);
        
    }//GEN-LAST:event_addActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add_sale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add_sale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add_sale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add_sale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new add_sale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JLabel ic;
    public javax.swing.JTextField item_code;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel pan;
    public javax.swing.JTextField party_name;
    private javax.swing.JLabel pie;
    public javax.swing.JTextField piece;
    private javax.swing.JLabel pn;
    public javax.swing.JTextField pro_name;
    private javax.swing.JLabel ra;
    public javax.swing.JTextField rate;
    public javax.swing.JTextField sell_date;
    // End of variables declaration//GEN-END:variables
}
