/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package window;

import data.*;

/**
 *
 * @author Bhadresh
 */
public class add_production extends javax.swing.JFrame {

    /**
     * Creates new form purchase
     */
    add_production p;
    
    public add_production() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pro_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        party_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        mat_name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        mat_weight = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        rm_date = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        pro_piece = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        wop = new javax.swing.JTextField();
        grin = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        waste = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Material Weight");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 183, 80, -1));
        jPanel1.add(pro_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 120, -1));

        jLabel2.setText("Product Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 143, 80, -1));
        jPanel1.add(party_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 120, -1));

        jLabel3.setText("Material Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 103, 80, -1));
        jPanel1.add(mat_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 120, -1));

        jLabel4.setText("Party Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 63, 80, -1));
        jPanel1.add(mat_weight, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 120, -1));

        jLabel6.setText("Raw Material Date");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 23, 110, -1));
        jPanel1.add(rm_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 120, -1));

        add.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        add.setText("Add Product Detail");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 260, 30));

        jLabel9.setText("Product Pis");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 224, 80, -1));
        jPanel1.add(pro_piece, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 120, -1));

        jLabel10.setText("Weight of  Pis");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 264, 80, -1));
        jPanel1.add(wop, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 120, -1));
        jPanel1.add(grin, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 120, -1));

        jLabel11.setText("Grinding");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 304, 110, -1));

        jLabel12.setText("Waste");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 344, 110, -1));
        jPanel1.add(waste, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 120, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed

        db_connection c = new db_connection(this);
        c.insert_production_query();
        setVisible(false);
        
    }//GEN-LAST:event_addActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add_production.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add_production.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add_production.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add_production.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new add_production().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    public javax.swing.JTextField grin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField mat_name;
    public javax.swing.JTextField mat_weight;
    public javax.swing.JTextField party_name;
    public javax.swing.JTextField pro_name;
    public javax.swing.JTextField pro_piece;
    public javax.swing.JTextField rm_date;
    public javax.swing.JTextField waste;
    public javax.swing.JTextField wop;
    // End of variables declaration//GEN-END:variables
}
