/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package window;

import data.db_connection;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.sql.ResultSet;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;

/**
 *
 * @author Bhadresh
 */
public class add_purchase extends javax.swing.JFrame {

    /**
     * Creates new form add_purchase
     */
    add_purchase ap;
    public db_connection dc = new db_connection();
    DefaultComboBoxModel model;
    
    public add_purchase() {
        initComponents();
        dc.makeconnection();
        model = new DefaultComboBoxModel(fillcombo());
        party_name.setModel(model);
    }
    
    public String[] fillcombo()
    {
        String[] resultArray = null;
        
        try{
           dc.stmt = dc.conn.createStatement();
           String sql;
           ResultSet rs;
           int i = 0;
           int size = 0;
           
           sql = "SELECT COUNT(*) FROM vendor";
           rs = dc.stmt.executeQuery(sql);
           
           while(rs.next())
           {
               size = rs.getInt(1);
           }
           
           System.out.println(size);
           resultArray = new String[size];
           
           sql = "SELECT party_name FROM vendor ORDER BY party_name";
           rs = dc.stmt.executeQuery(sql);
           
           while(rs.next())
           {
               resultArray[i] = rs.getString(1);
               System.out.println(rs.getString(1));
               i++;
           }
           
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        return resultArray;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pur_date = new javax.swing.JTextField();
        mat_name = new javax.swing.JTextField();
        rate = new javax.swing.JTextField();
        weight = new javax.swing.JTextField();
        expe = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        a = new javax.swing.JButton();
        party_name = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Purchase Date");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 80, -1));
        jPanel1.add(pur_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 120, -1));
        jPanel1.add(mat_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 120, -1));
        jPanel1.add(rate, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 120, -1));
        jPanel1.add(weight, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 120, -1));
        jPanel1.add(expe, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 120, -1));

        add.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        add.setText("Add Purchase Detail");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 250, 30));

        jLabel5.setText("Expense");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 233, 80, -1));

        jLabel1.setText("Weight");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 193, 80, -1));

        jLabel2.setText("Rate");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 154, 80, -1));

        jLabel3.setText("Material Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 80, -1));

        jLabel4.setText("Party Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 80, -1));

        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });
        jPanel1.add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 20, 20));
        try {
            Image img = ImageIO.read(getClass().getResource("/add.png"));
            Image newimg = img.getScaledInstance( 10 , 10,  java.awt.Image.SCALE_SMOOTH ) ;
            a.setIcon(new ImageIcon(newimg));
        } catch (IOException ex) {
        }

        jPanel1.add(party_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 120, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed

        db_connection c = new db_connection(this);
        c.insert_purchase_query();
        setVisible(false);
    }//GEN-LAST:event_addActionPerformed

    private void aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aActionPerformed
        
       add_vendor av = new add_vendor();
       av.setAlwaysOnTop(true);
       Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
       this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
       av.setVisible(true);
       av.pack();
       av.setLocationRelativeTo(null);
    }//GEN-LAST:event_aActionPerformed

    /**
  11   * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add_purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add_purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add_purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add_purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new add_purchase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton a;
    private javax.swing.JButton add;
    public javax.swing.JTextField expe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField mat_name;
    public javax.swing.JComboBox party_name;
    public javax.swing.JTextField pur_date;
    public javax.swing.JTextField rate;
    public javax.swing.JTextField weight;
    // End of variables declaration//GEN-END:variables
}
