/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package window;

import data.db_connection;
import java.sql.ResultSet;

/**
 *
 * @author Bhadresh
 */
public class edit_vendor extends javax.swing.JFrame {

    /**
     * Creates new form add_purchase
     */
    edit_vendor ep;
    public db_connection dc = new db_connection();
    
    public edit_vendor() {
        initComponents();
        dc.makeconnection();
        fillcombo();
    }

    public void fillcombo()
    {
        try{
           dc.stmt = dc.conn.createStatement();
           String sql;

           sql = "SELECT * FROM vendor";
           ResultSet rs = dc.stmt.executeQuery(sql);

           while(rs.next())
           {
               int vid = rs.getInt("v_id");
               s_no.addItem(vid);
           }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        party_name = new javax.swing.JTextField();
        mob = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        s_no = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        addr = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(party_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 170, -1));
        jPanel1.add(mob, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 170, -1));
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 170, -1));

        add.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        add.setText("Edit Vendor Detail");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 300, 30));

        jLabel5.setText("Email ID");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 263, 80, -1));

        jLabel1.setText("Mobile No.");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 223, 80, -1));

        jLabel4.setText("Address");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 105, 80, -1));

        jLabel7.setText("Serial No.");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 23, 80, -1));

        s_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_noActionPerformed(evt);
            }
        });
        jPanel1.add(s_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 170, 22));

        addr.setColumns(20);
        addr.setRows(5);
        jScrollPane1.setViewportView(addr);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 170, 100));

        jLabel6.setText("Party Name");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 64, 80, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed

        db_connection c = new db_connection(this);
        c.insert_evendor_query();
        setVisible(false);
    }//GEN-LAST:event_addActionPerformed

    private void s_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_noActionPerformed
       
        fill_details(Integer.parseInt(s_no.getSelectedItem().toString()));
    }//GEN-LAST:event_s_noActionPerformed

    private void fill_details(int vid)
    {
        try{
           dc.stmt = dc.conn.createStatement();
           String sql;

           sql = "SELECT * FROM vendor WHERE v_id ='" + vid + "';";
           ResultSet rs = dc.stmt.executeQuery(sql);

           while(rs.next())
           {
               party_name.setText(rs.getString("party_name"));
               addr.setText(rs.getString("address"));
               mob.setText(rs.getString("mobile_no"));               
               email.setText(rs.getString("email"));
           }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(edit_vendor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(edit_vendor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(edit_vendor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(edit_vendor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new edit_vendor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    public javax.swing.JTextArea addr;
    public javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField mob;
    public javax.swing.JTextField party_name;
    public javax.swing.JComboBox s_no;
    // End of variables declaration//GEN-END:variables
}
