/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package window;

import data.db_connection;
import java.sql.ResultSet;

/**
 *
 * @author Bhadresh
 */
public class edit_purchase extends javax.swing.JFrame {

    /**
     * Creates new form add_purchase
     */
    edit_purchase ep;
    public db_connection dc = new db_connection();
    
    public edit_purchase() {
        initComponents();
        dc.makeconnection();
        fillcombo();
    }

    public void fillcombo()
    {
        try{
           dc.stmt = dc.conn.createStatement();
           String sql;

           sql = "SELECT * FROM purchase";
           ResultSet rs = dc.stmt.executeQuery(sql);

           while(rs.next())
           {
               int pid = rs.getInt("p_id");
               s_no.addItem(pid);
           }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pur_date = new javax.swing.JTextField();
        party_name = new javax.swing.JTextField();
        mat_name = new javax.swing.JTextField();
        rate = new javax.swing.JTextField();
        weight = new javax.swing.JTextField();
        expe = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        s_no = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Purchase Date");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 63, 80, -1));
        jPanel1.add(pur_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 120, -1));
        jPanel1.add(party_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 120, -1));
        jPanel1.add(mat_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 120, -1));
        jPanel1.add(rate, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 120, -1));
        jPanel1.add(weight, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 120, -1));
        jPanel1.add(expe, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 120, -1));

        add.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        add.setText("Edit Detail");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 250, 30));

        jLabel5.setText("Expense");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 263, 80, -1));

        jLabel1.setText("Weight");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 223, 80, -1));

        jLabel2.setText("Rate");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 183, 80, -1));

        jLabel3.setText("Material Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 143, 80, -1));

        jLabel4.setText("Party Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 103, 80, -1));

        jLabel7.setText("Serial No.");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 23, 80, -1));

        s_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_noActionPerformed(evt);
            }
        });
        jPanel1.add(s_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 120, 22));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed

        db_connection c = new db_connection(this);
        c.insert_epurchase_query();
        setVisible(false);
    }//GEN-LAST:event_addActionPerformed

    private void s_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_noActionPerformed
       
        fill_details(Integer.parseInt(s_no.getSelectedItem().toString()));
    }//GEN-LAST:event_s_noActionPerformed

    private void fill_details(int pid)
    {
        try{
           dc.stmt = dc.conn.createStatement();
           String sql;

           sql = "SELECT * FROM purchase WHERE p_id ='" + pid + "';";
           ResultSet rs = dc.stmt.executeQuery(sql);

           while(rs.next())
           {
               pur_date.setText(rs.getString("date"));
               party_name.setText(rs.getString("party_name"));
               mat_name.setText(rs.getString("material_name"));
               rate.setText(Float.toString(rs.getFloat("rate")));               
               weight.setText(Float.toString(rs.getFloat("weight")));
               expe.setText(Integer.toString(rs.getInt("expense")));
           }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(edit_purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(edit_purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(edit_purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(edit_purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new edit_purchase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    public javax.swing.JTextField expe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField mat_name;
    public javax.swing.JTextField party_name;
    public javax.swing.JTextField pur_date;
    public javax.swing.JTextField rate;
    public javax.swing.JComboBox s_no;
    public javax.swing.JTextField weight;
    // End of variables declaration//GEN-END:variables
}
