
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package window;

import data.db_connection;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bhadresh
 */
public class sales_home extends javax.swing.JFrame {

//    /**
//     * Creates new form purchase_home
//     */ // JDBC driver name and database URL
//   static final String JDBC_DRIVER = "com.mysql.jdbc.Driver";  
//   static final String DB_URL = "jdbc:mysql://127.0.0.1:3306/my_db";
//
//   //  Database credentials
//   static final String USER = "root";
//   static final String PASS = "1234";
    sales_home p;
    public db_connection dc = new db_connection();
    
    
    public sales_home() {
        initComponents();
        dc.makeconnection();
        doMyAction();
    }

    public void doMyAction()
    {
       DefaultTableModel model = (DefaultTableModel)sales.getModel();
       
       
       try{
       dc.stmt = dc.conn.createStatement();
       String sql;

       sql = "SELECT * FROM sales";
       ResultSet rs = dc.stmt.executeQuery(sql);

       while(rs.next())
       {
           int sid = rs.getInt("s_id");
           String party_name = rs.getString("party_name");
           String pro_name = rs.getString("product_name");
           String item_code = rs.getString("item_code");
           int piece  = rs.getInt("piece");
           float rate = rs.getFloat("rate");
           float amount = rs.getInt("amount");
           float amount_due = rs.getInt("amount_due");
           String payment_status = rs.getString("status");

           model.addRow(new Object[]{sid,party_name,pro_name,item_code,piece,rate,amount,amount_due,payment_status});
        }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sales = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        selling = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        refresh = new javax.swing.JButton();
        payment = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Selling");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial No.", "Party Name", "Product Name", "Item Code", "Piece", "Rate", "Amount", "Amount Due", "Payment Status"
            }
        ));
        sales.setEnabled(false);
        jScrollPane1.setViewportView(sales);
        if (sales.getColumnModel().getColumnCount() > 0) {
            sales.getColumnModel().getColumn(8).setPreferredWidth(80);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 600));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 760, 600));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        selling.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        selling.setText("Selling");
        selling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellingActionPerformed(evt);
            }
        });
        jPanel2.add(selling, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 110, 30));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jLabel5.setText("Select Options");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 6, 90, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 29, 190, 11));

        refresh.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        jPanel2.add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 110, 30));

        payment.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        payment.setText("Payment");
        payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentActionPerformed(evt);
            }
        });
        jPanel2.add(payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 110, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sellingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellingActionPerformed
        
       add_sale as = new add_sale();
       as.setAlwaysOnTop(true);
       Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
       this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
       as.setVisible(true);
       as.pack();
       as.setLocationRelativeTo(null);
    }//GEN-LAST:event_sellingActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        
        do_refresh();
    }//GEN-LAST:event_refreshActionPerformed

    private void paymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentActionPerformed
        
       sales_payment sp = new sales_payment();
       sp.setAlwaysOnTop(true);
       Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
       this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
       sp.setVisible(true);
       sp.pack();
       sp.setLocationRelativeTo(null);
    }//GEN-LAST:event_paymentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sales_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sales_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sales_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sales_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sales_home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton payment;
    private javax.swing.JButton refresh;
    public javax.swing.JTable sales;
    private javax.swing.JButton selling;
    // End of variables declaration//GEN-END:variables

    private void do_refresh() {
    
       DefaultTableModel model = (DefaultTableModel)sales.getModel();
       
       int rowCount = model.getRowCount();
       for (int i = rowCount - 1; i >= 0; i--)
       {
        model.removeRow(i);
       }
       
       try{
       dc.stmt = dc.conn.createStatement();
       String sql;

       sql = "SELECT * FROM sales";
       ResultSet rs = dc.stmt.executeQuery(sql);

       while(rs.next())
       {
           int sid = rs.getInt("s_id");
           String party_name = rs.getString("party_name");
           String pro_name = rs.getString("product_name");
           String item_code = rs.getString("item_code");
           int piece  = rs.getInt("piece");
           float rate = rs.getFloat("rate");
           float amount = rs.getInt("amount");
           float amount_due = rs.getInt("amount_due");
           String payment_status = rs.getString("status");

           model.addRow(new Object[]{sid,party_name,pro_name,item_code,piece,rate,amount,amount_due,payment_status});
        }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    
    }
}
