
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package window;

import data.db_connection;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bhadresh
 */
public class transaction_home extends javax.swing.JFrame {

//    /**
//     * Creates new form purchase_home
//     */ // JDBC driver name and database URL
//   static final String JDBC_DRIVER = "com.mysql.jdbc.Driver";  
//   static final String DB_URL = "jdbc:mysql://127.0.0.1:3306/my_db";
//
//   //  Database credentials
//   static final String USER = "root";
//   static final String PASS = "1234";
    transaction_home p;
    public db_connection dc = new db_connection();
    
    
    public transaction_home() {
        initComponents();
        dc.makeconnection();
        doMyAction();
    }

    public void doMyAction()
    {
       DefaultTableModel model = (DefaultTableModel)transaction.getModel();
       
       
       try{
       dc.stmt = dc.conn.createStatement();
       String sql;
       ResultSet rs;
       
       sql = "SELECT * FROM transaction";
       rs = dc.stmt.executeQuery(sql);

       while(rs.next())
       {
           int pid = rs.getInt("pay_id");
           String pay_date = rs.getString("payment_date");
           String p_name = rs.getString("party_name");
           String tra = rs.getString("transaction");
           String type = rs.getString("type");
           int c_no  = rs.getInt("check_no");
           String b_name = rs.getString("bank_name");
           float amt = rs.getFloat("amount");

          model.addRow(new Object[]{pay_date,p_name,tra,type,c_no,b_name,amt});
        }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        transaction = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        selling = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        refresh = new javax.swing.JButton();
        payment = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Selling");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        transaction.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Party Name", "Transaction", "Type", "Check No", "Bank Name", "Amount"
            }
        ));
        transaction.setEnabled(false);
        jScrollPane1.setViewportView(transaction);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 700, 600));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        selling.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        selling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellingActionPerformed(evt);
            }
        });
        jPanel2.add(selling, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 110, 30));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jLabel5.setText("Select Options");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 6, 90, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 29, 190, 11));

        refresh.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        jPanel2.add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 110, 30));

        payment.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentActionPerformed(evt);
            }
        });
        jPanel2.add(payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 110, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sellingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellingActionPerformed

    }//GEN-LAST:event_sellingActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        
        do_refresh();
    }//GEN-LAST:event_refreshActionPerformed

    private void paymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paymentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transaction_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transaction_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transaction_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transaction_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transaction_home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton payment;
    private javax.swing.JButton refresh;
    private javax.swing.JButton selling;
    public javax.swing.JTable transaction;
    // End of variables declaration//GEN-END:variables

    private void do_refresh() {
    
       DefaultTableModel model = (DefaultTableModel)transaction.getModel();
       
       int rowCount = model.getRowCount();
       for (int i = rowCount - 1; i >= 0; i--)
       {
        model.removeRow(i);
       }
       
       try{
       dc.stmt = dc.conn.createStatement();
       String sql;

       sql = "SELECT * FROM transaction";
       ResultSet rs = dc.stmt.executeQuery(sql);

       while(rs.next())
       {
           int pid = rs.getInt("pay_id");
           String pay_date = rs.getString("payment_date");
           String p_name = rs.getString("party_name");
           String tra = rs.getString("transaction");
           String type = rs.getString("type");
           int c_no  = rs.getInt("check_no");
           String b_name = rs.getString("bank_name");
           float amt = rs.getFloat("amount");

          model.addRow(new Object[]{pay_date,p_name,type,c_no,b_name,amt});
        }
       }
       catch(Exception e)
       {
           e.printStackTrace();
       }
    
    }
}
